server:
  port: 8787
  shutdown: graceful

spring:
  profiles:
    active: docker,eureka,kafka

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS

feign:
  egoviskm:
    url: 'https://iskm.egov.uz:9444'
    name: 'iskm.egov.uz'
    basic:
      username: 'F6wHgzC1_dzucM9AmO1IO_Yz9uka'
      password: '6LTqoPlZcDZtJBRHnBfCRbUfkjYa'
    username: 'mintrans-statistika'
    password: '1azq7Kb3GLcDAAThRwVv'
  egovmgw:
    url: 'https://apimgw.egov.uz:8243'
    name: 'apimgw.egov.uz'
  eskiz:
    url: 'https://notify.eskiz.uz'
    name: 'eskiz'
    email: 'azamat_zhuraev@mail.ru'
    password: 'yvMUfgFaWTlvNUuHLpsrKmGKCKaL683lUg5JKIU5'


application:
  version: ${version}
  whitelist:
    - '/actuator'
    - '/actuator/**'
    - '/v3/api-docs/**'
    - '/swagger-ui/**'
    - '/swagger-ui.html'
    - '/eureka/**'

resilience4j:
  circuitbreaker:
    instances:
      eskiz:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      eskism:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      egovCarInfo:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      mehnat:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      taxCompanyInfo:
        registerHealthIndicator: true
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
