spring:
  data:
    mongodb:
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/?authSource=admin
      host: localhost
      port: 37017
      username: root
      password: rootpassword
      database: ticket
      uuid-representation: standard

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/waybill_driver
    username: postgres
    password: waybill_pwd
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration/structure
    schemas: public