server:
  port: 8787
  shutdown: graceful

spring:
  profiles:
    active: database,docker,eureka,oauth2,kafka,open-api,circuitbreaker

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: ALWAYS


application:
  version: ${version}
  adminCompanyId: 'b627bc73-ae76-46c4-84bc-8eeb77653dc1'
  whitelist:
    - '/actuator'
    - '/actuator/**'
    - '/v3/api-docs/**'
    - '/swagger-ui/**'
    - '/swagger-ui.html'
    - '/eureka/**'

gateway:
  url: http://localhost:8080
