spring:
  kafka:
    bootstrap-servers: 192.168.88.237:9092
    producer:
      properties:
        spring.json.trusted.packages: '*'
    consumer:
      group-id: to_user_service
      auto-offset-reset: earliest