server:
  port: 8020
  shutdown: graceful

spring:
  profiles:
    active: admin,database,docker,eureka,keycloak,oauth2,open-api,kafka
  jackson:
    default-property-inclusion: non_null

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

application:
  whitelist:
    - '/api/v1/auth-user/reset/password'
    - '/api/v1/otp/send'
    - '/api/v1/auth-admin/register'
    - '/api/v1/auth-user/token'
    - '/api/v1/auth-user/refresh-token'
    - '/actuator'
    - '/actuator/**'
    - '/eureka/**'

otp:
  length: 5
  valid-time-seconds: 180

admin-company:
  viewer-company-id: 'b627bc73-ae76-46c4-84bc-8eeb77653dc1'
