spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://195.158.2.76:15436/keycloak_v1
    username: postgres
    password: keycloak2024
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration/structure

