server:
  port: 8030
  shutdown: graceful

spring:
  application:
    name: WAYBILL-FILE-SERVICE
  profiles:
    active:
      - admin
      - database
      - docker
      - eureka
      - oauth2
      - open-api

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS