server:
  port: 8030
  shutdown: graceful

spring:
  profiles:
    active: admin,database,docker,eureka,oauth2,open-api

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS