server:
  port: 8050
  shutdown: graceful

spring:
  profiles:
    active: admin,database,docker,eureka,oauth2,open-api,kafka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


application:
  version: ${version}
  whitelist:
    - '/actuator'
    - '/actuator/**'
    - '/v3/api-docs'
    - '/v3/api-docs/**'
    - '/swagger-ui/**'
    - '/swagger-ui.html'
    - '/eureka/**'

cors:
  allowedHeaders: [ "Accept", "Accept-Language", "Origin", "x-language","Content-Language", "Content-Type", "X-Requested-With", "Authorization" , "Referer"]
  allowedOrigins: ["*"]
  allowedOriginPatterns: ["http://localhost:*", "https://*.waybill.uz"]
  allowedMethods: [ "GET", "POST", "PUT", "DELETE", "PATCH", "OPTIONS", "HEAD" ]
  allowCredentials: true
  exposedHeaders: [ "X-Total-Count", "Content-Disposition" ]
  urlPattern: "/**"
