server:
  port: 8050
  shutdown: graceful

spring:
  profiles:
    active: admin,database,docker,eureka,oauth2,open-api,kafka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


application:
  version: ${version}
  adminCompanyId: 'b627bc73-ae76-46c4-84bc-8eeb77653dc1'
  whitelist:
    - '/actuator'
    - '/actuator/**'
    - '/v3/api-docs'
    - '/v3/api-docs/**'
    - '/swagger-ui/**'
    - '/swagger-ui.html'
    - '/eureka/**'
