spring:
  data:
    mongodb:
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/?authSource=admin
      host: 192.168.88.246
      port: 3676
      database: driver
      password: WBDriver24
      username: driver
      uuid-representation: standard