spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.88.246:5436/waybill_driver
    username: postgres
    password: waybill_pwd
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration/structure
      - classpath:db/migration/data
    schemas: public
