server:
  port: 8888
  shutdown: graceful

spring:
  boot:
    admin:
      client:
        instance:
          service-url: lb://WAYBILL-ADMIN-SERVICE

  security:
    user:
      name: waybill_config
      password: waybill_pwd

eureka:
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 60
    leaseExpirationDurationInSeconds: 60
  client:
    service-url:
      defaultZone: http://eureka:eureka_pwd@${eureka.instance.hostname}:8761/eureka/
    registryFetchIntervalSeconds: 60
