server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    active:
        - admin
        - circuit-breaker
        - docker
        - eureka
        - routes
        - oauth2
        - open-api
        - whitelist

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
