server:
  port: 8080
  shutdown: graceful

spring:
  profiles:
    active:
        - prod-admin
        - prod-circuit-breaker
        - prod-docker
        - prod-eureka
        - prod-routes
        - prod-oauth2
        - prod-open-api
        - prod-whitelist

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
