spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:35432/waybill_file
    username: postgres
    password: waybill_pwd
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration/structure
    schemas: public



#Todo: need to be updated from JPA to Spring JDBS