server:
  port: 8010
  shutdown: graceful

spring:
  profiles:
    active: admin,database,docker,eureka,oauth2,open-api,kafka
  jackson:
    default-property-inclusion: non_null


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS


application:
  whitelist:
    - '/actuator'
    - '/actuator/**'
    - '/v3/api-docs'
    - '/v3/api-docs/**'
    - '/swagger-ui/**'
    - '/swagger-ui.html'
    - '/eureka/**'