eureka:
  instance:
    hostname: 192.168.88.244
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 10
  client:
    service-url:
      defaultZone: http://eureka:eureka_pwd@${eureka.instance.hostname}:8761/eureka/
    registryFetchIntervalSeconds: 10