spring:
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://keycloak.dtransport.uz/realms/waybill
#          jwk-set-uri: https://keycloak.dtransport.uz/realms/waybill/protocol/openid-connect/certs
      client:
        provider:
          keycloak:
            issuer-uri: https://keycloak.dtransport.uz/realms/waybill
        registration:
          waybill-oauth2:
            provider: keycloak
            client-id: waybill-id
            client-secret: aa1XwVCl18HWw5XtQRvZepQ8vC1QuUWw
            authorization-grant-type: authorization_code
            scope:
              - openid
              - discovery
