spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      default-filters:
        - TokenRelay=
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - 'http://localhost'
              - 'http://192.168.88.244'
            allow-credentials: true
            allowedHeaders: '*'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - OPTIONS

      routes:
        - id: user-service
          uri: lb://WAYBILL-USER-SERVICE-local
          predicates:
            - Path=/user-service/v3/api-docs, /user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: circuit-breaker-config
                fallbackUri: forward:/fallback/user-service

        - id: vehicle-service
          uri: lb://WAYBILL-VEHICLE-SERVICE-local
          predicates:
            - Path=/vehicle-service/v3/api-docs, /vehicle-service/**
          filters:
            - RewritePath=/vehicle-service/(?<suburl>.*),/${suburl}
            - name: CircuitBreaker
              args:
                name: vehicleServiceFallBack
                fallbackUri: forward:/fallback/vehicle-service

        - id: file-service
          uri: lb://WAYBILL-FILE-SERVICE-local
          predicates:
            - Path=/file-service/v3/api-docs, /file-service/**
          filters:
            - RewritePath=/file-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: fileServiceFallBack
                fallbackUri: forward:/fallback/file-service

        - id: driver-service
          uri: lb://WAYBILL-DRIVER-SERVICE-local
          predicates:
            - Path=/driver-service/v3/api-docs, /driver-service/**
          filters:
            - RewritePath=/driver-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: driverServiceFallBack
                fallbackUri: forward:/fallback/driver-service

        - id: ticket-service
          uri: lb://WAYBILL-TICKET-SERVICE-local
          predicates:
            - Path=/ticket-service/v3/api-docs, /ticket-service/**
          filters:
            - RewritePath=/ticket-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: driverServiceFallBack
                fallbackUri: forward:/fallback/ticket-service

        - id: inspection-service
          uri: lb://WAYBILL-INSPECTION-SERVICE-local
          predicates:
            - Path=/inspection-service/v3/api-docs, /inspection-service/**
          filters:
            - RewritePath=/inspection-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: driverServiceFallBack
                fallbackUri: forward:/fallback/inspection-service

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
