whitelist:
  gateway:
    - '/swagger-ui.html'
    - '/webjars/swagger-ui/**'
    - '/swagger-ui/**'
    - '/swagger-doc/**'
    - '/swagger-resources/**'
    - '/actuator/health'
    - '/actuator/metrics'
    - '/actuator/metrics/**'
    - '/v3/api-docs/**'
    - '/eureka/**'

  userService:
    - '/user-service/swagger-ui.html'
    - '/user-service/webjars/swagger-ui/**'
    - '/user-service/swagger-ui/**'
    - '/user-service/swagger-doc/**'
    - '/user-service/swagger-resources/**'
    - '/user-service/actuator/health'
    - '/user-service/actuator/metrics'
    - '/user-service/actuator/metrics/**'
    - '/user-service/v3/api-docs/**'
    - '/user-service/eureka/**'
    - '/user-service/v3/api-docs'
    - '/user-service/api/v1/auth-user/token'
    - '/user-service/api/v1/auth-user/refresh-token'

  vehicleService:
    - '/vehicle-service/swagger-ui.html'
    - '/vehicle-service/webjars/swagger-ui/**'
    - '/vehicle-service/swagger-ui/**'
    - '/vehicle-service/swagger-doc/**'
    - '/vehicle-service/swagger-resources/**'
    - '/vehicle-service/actuator/health'
    - '/vehicle-service/actuator/metrics'
    - '/vehicle-service/actuator/metrics/**'
    - '/vehicle-service/v3/api-docs/**'
    - '/vehicle-service/eureka/**'
    - '/vehicle-service/v3/api-docs'

  ticket-service:
    - '/ticket-service/webjars/swagger-ui/**'
    - '/ticket-service/swagger-ui/**'
    - '/ticket-service/swagger-doc/**'
    - '/ticket-service/swagger-resources/**'
    - '/ticket-service/actuator/health'
    - '/ticket-service/actuator/metrics'
    - '/ticket-service/actuator/metrics/**'
    - '/ticket-service/v3/api-docs/**'
    - '/ticket-service/eureka/**'
    - '/ticket-service/v3/api-docs'

  driverService:
    - '/driver-service/swagger-ui.html'
    - '/driver-service/webjars/swagger-ui/**'
    - '/driver-service/swagger-ui/**'
    - '/driver-service/swagger-doc/**'
    - '/driver-service/swagger-resources/**'
    - '/driver-service/actuator/health'
    - '/driver-service/actuator/metrics'
    - '/driver-service/actuator/metrics/**'
    - '/driver-service/v3/api-docs/**'
    - '/driver-service/eureka/**'
    - '/driver-service/v3/api-docs'
