spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      default-filters:
        - TokenRelay=

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://192.168.88.244"
              - "http://192.168.88.244:80"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS

      routes:
        - id: user-service
          uri: lb://WAYBILL-USER-SERVICE-PROD
          predicates:
            - Path=/user-service/v3/api-docs, /user-service/**
          filters:
            - RewritePath=/user-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: circuit-breaker-config
                fallbackUri: forward:/fallback/user-service

        - id: vehicle-service
          uri: lb://WAYBILL-VEHICLE-SERVICE-PROD
          predicates:
            - Path=/vehicle-service/v3/api-docs, /vehicle-service/**
          filters:
            - RewritePath=/vehicle-service/(?<suburl>.*),/${suburl}
            - name: CircuitBreaker
              args:
                name: vehicleServiceFallBack
                fallbackUri: forward:/fallback/vehicle-service

        - id: file-service
          uri: lb://WAYBILL-FILE-SERVICE-PROD
          predicates:
            - Path=/file-service/v3/api-docs, /file-service/**
          filters:
            - RewritePath=/file-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: fileServiceFallBack
                fallbackUri: forward:/fallback/file-service

        - id: driver-service
          uri: lb://WAYBILL-DRIVER-SERVICE-PROD
          predicates:
            - Path=/driver-service/v3/api-docs, /driver-service/**
          filters:
            - RewritePath=/driver-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: driverServiceFallBack
                fallbackUri: forward:/fallback/driver-service

        - id: ticket-service
          uri: lb://WAYBILL-TICKET-SERVICE-PROD
          predicates:
            - Path=/ticket-service/v3/api-docs, /ticket-service/**
          filters:
            - RewritePath=/ticket-service/(?<path>.*), /$\{path}
            - name: CircuitBreaker
              args:
                name: driverServiceFallBack
                fallbackUri: forward:/fallback/ticket-service


        - id: openapi
          uri: http://192.168.88.244:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
