keycloak:
  auth-adm-username: admin
  auth-adm-password: Keycloak2024
  auth-server-url: https://keycloak.dtransport.uz #/auth
  auth-realm: master
  auth-client-id: alid
  auth-client-secret: YAo4nbeJqlcQ2qnffklq0QR1NPvKOtBf